resources:
  containers:
  - container: pi-gen
    image: wpilib/pi-gen:latest

jobs:
 - job: 'Main'
   pool:
     vmImage: 'Ubuntu 16.04'

   container: pi-gen

   steps:
      - checkout: self
        submodules: true
      - script: |
          cd deps && ./01-download.sh && ./02-extract.sh && ./03-build.sh && ./04-copy.sh
        displayName: 'Build Image Dependencies'
      - script: |
          dpkg-reconfigure qemu-user-static
          ./build.sh
        displayName: 'Build Image'
      - task: CopyFiles@2
        inputs:
          contents: 'deploy/*.zip'
          targetFolder: $(Build.ArtifactStagingDirectory)
      - task: PublishBuildArtifacts@1
        inputs:
          artifactName: 'FRCVisionImage'
